controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
#  - group: left_arm
#    pose: home

  []