left_manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_left
    - l_joint_1
    - l_joint_2
    - l_joint_3
    - l_joint_4
    - l_joint_5
    - l_joint_6
  gains:
    joint_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_right
    - r_joint_1
    - r_joint_2
    - r_joint_3
    - r_joint_4
    - r_joint_5
    - r_joint_6
  gains:
    joint_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1